.TH "OWLOWISCIOUS" "8" "2014-07-30" "GNU Pony" "GNU Pony Manual"
.SH NAME
owlowiscious - Your nighttime alternative to Spike
.SH "SYNOPSIS"
.B
owlowiscious
.I
<COMMAND>
[\fIOPTION\fR]...
.SH "DESCRIPTION"
.PP
Spike, a dragon, is a diurnal creature: he is awake
during the day and asleep during the night. The give
Spike a proper good nights sleep Twilight, a seriously
overactive yet not hyperactive pony, got another
assistant --- owlowiscious --- who is an owl, a
famously nocturnal creature. Thus during the night
Spike is complemented by Owlowiscious.
.PP
Keep in mind that Spike has low confidence, and will
think he is replaced and not needed anymore if you
utilise Owlowiscious too much.
.PP
You can speak to Owlowiscious in the same way you
speek to Spike. Just because it always says 'Who?'
and nothing else, it does not mean he does not
understand you.
.SH "AUTHORS"
.PP
Written by Mattias Andrée <maandree@member.fsf.org>.
.SH "SEE ALSO"
.TP
\fBspike\fR(8)
.SH "COPYRIGHT"
.PP
Copyright (C) 2014  Mattias Andrée
.PP
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3
or any later version published by the Free Software Foundation;
with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
A copy of the license is included in the section entitled "GNU
Free Documentation License".
